# Generated by Django 4.2.7 on 2024-05-02 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot_album', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='artista',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
