# Generated by Django 4.2.7 on 2024-05-02 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spot_album', '0003_album_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='image',
            new_name='capa',
        ),
    ]
