# Generated by Django 5.0.4 on 2024-08-12 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot_album', '0005_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
