# Generated by Django 4.2.7 on 2024-05-02 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot_album', '0006_alter_album_capa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='capa',
            field=models.ImageField(blank=True, default='images/blank.png', upload_to='upload/images'),
        ),
    ]
