# Generated by Django 5.0.4 on 2024-08-12 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spot_album', '0006_alter_friends_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friends',
            unique_together={('user_id', 'user_id_2')},
        ),
    ]
