# Generated by Django 4.2.7 on 2024-08-18 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spot_album', '0007_alter_friends_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='date',
        ),
    ]
