# Generated by Django 4.2.7 on 2024-08-18 16:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spot_album', '0008_remove_friends_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
