# Generated by Django 4.2.7 on 2024-09-03 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot_album', '0009_friends_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='artwork',
            field=models.ImageField(blank=True, null=True, upload_to='upload/images'),
        ),
    ]
