# Generated by Django 4.2.7 on 2024-07-21 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot_album', '0011_publication_delete_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='category',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='title',
        ),
        migrations.AddField(
            model_name='publication',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
