# Generated by Django 4.2.7 on 2024-07-21 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot_album', '0012_remove_publication_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('comment_artwork', models.ImageField(blank=True, default='blank.png', null=True, upload_to='upload/images')),
            ],
        ),
    ]
