# Generated by Django 4.2.7 on 2024-07-26 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot_album', '0014_comments_pub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='artwork',
            field=models.ImageField(default='blank.png', upload_to='upload/images'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
