# Generated by Django 4.2.7 on 2024-07-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot_album', '0015_alter_publication_artwork_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='artwork',
            field=models.ImageField(blank=True, default='blank.png', null=True, upload_to='upload/images'),
        ),
    ]
