# Generated by Django 4.2.7 on 2024-07-27 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot_album', '0016_alter_publication_artwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='title',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
