# Generated by Django 4.2.7 on 2024-07-27 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot_album', '0017_publication_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.TextField(),
        ),
    ]
