# Generated by Django 4.2.7 on 2024-07-27 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot_album', '0021_rename_title_post_publication_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='publication_date',
            field=models.DateField(default='2024-05-02'),
        ),
    ]
