# Generated by Django 4.2.7 on 2024-07-27 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot_album', '0022_comments_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='publication_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
