# Generated by Django 4.2.7 on 2024-07-27 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spot_album', '0023_alter_comments_publication_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='publication_date',
            new_name='comments_date',
        ),
    ]
